### ISSUE TITLE
fwrite to php://stderr throws E_NOTICE on php 7.4

### ISSUE THREAD

**Issue by miranovy** [nette/tester#420] opened 2020-07-07 09:35 UTC
Version: 2.3.2

### Bug Description
Function `fwrite` to `php://stderr` throws `E_NOTICE` on php 7.4. On php 7.3 and 7.2 behaves correctly.

### Steps To Reproduce
```php
<?php declare(strict_types=1);

namespace Tests;

use Tester\Assert;
use Tester\TestCase;

$container = require __DIR__ . '/../bootstrap.php';

class FwriteTest extends TestCase
{
    public function testPhpStderr()
    {
	$fw = fopen('php://stderr', 'w');
	fwrite($fw, 'same text');
	fclose($fw);
    }
}

(new FwriteTest())->run();
```

```bash
vendor/bin/tester -s -p php --colors 1 -C fwrite.phpt 
 _____ ___  ___ _____ ___  ___
|_   _/ __)( __/_   _/ __)| _ )
  |_| \___ /___) |_| \___ |_|_\  v2.3.2

PHP 7.4.7 (cli) | php | 8 threads

F

-- FAILED: fwrite.phpt
   Exited with error code 255 (expected 0)
   E_NOTICE: fwrite(): write of 5 bytes failed with errno=32 Broken pipe
   
   in tests/Logger/fwrite.phpt(16) 
   in [internal function]Tester\TestCase->Tester\{closure}()
   in tests/Logger/fwrite.phpt(16) fwrite()
   in src/Framework/TestCase.php(143) Tests\FwriteTest->testPhpStderr()
   in src/Framework/TestCase.php(55) Tester\TestCase->runTest()
   in tests/Logger/fwrite.phpt(22) Tester\TestCase->run()


FAILURES! (1 test, 1 failure, 0.1 seconds)
```

Run test separately via `php fwrite.phpt` behaves as expected.

```
same text
Error: This test forgets to execute an assertion.
```

### Expected Behavior
Write text to stderr, same as run test separately.

**Comment by dg** [comment] 2020-07-07 12:52
It triggers E_NOTICE when strerr is closed since PHP 7.4. Maybe here https://github.com/nette/tester/blob/170b379e8609db3f9a5884b3e4048d6e27ec26cf/src/Runner/Job.php#L128 or below.

**Comment by milo** [comment] 2020-07-19 21:36
I remember there was a problem with stderr on Windows. If stderr output was too long, test got stuck. The reason was, that Windows somehow use the same output buffer (or something like that) for stdout and stderr and PHP got stuck on reading stdout when stderr was full and vice versa. It was in PHP 5.4 times. Not sure how about PHP 7.

Beside of that. Imagine that Job catches stdin and stdout, and test produces:
```
echo 1 > on stdout
echo 2 > on stderr
echo 3 > on stdout
echo 4 > on stderr
```
we are not able to reconstruct that in Runner output, there are not output timestamps. So we get:
```
echo 1 > on stdout
echo 3 > on stdout
echo 2 > on stderr
echo 4 > on stderr
```

**Comment by dg** [comment] 2020-07-20 10:24
The problem with stderr also affects PHP 7.4.

**Comment by JanTvrdik** [comment] 2020-07-20 13:26
related

**Comment by MartinMystikJonas** [comment] 2022-07-08 10:40
I just encountered this error too with PHP 8.1. We use Nette tester to test our dev-tools. When Nette tester calls command throught symfony console it ends with this error when it outputs last line to stderr. When we run test directly then it works. 

Any idea what might be the cause? It seems like stderr of test child process is for some reason closed prematurely by tester but I have no idea why.

**Comment by MartinMystikJonas** [comment] 2022-07-08 10:53
Ok after some digging it seems that reson is simple. Stderr of job is closed even before it is run here:
https://github.com/nette/tester/blob/fd9d510bfcc20acfc0e0cfa35fdb5109478b63d4/src/Runner/Job.php#L130

Is there any reson to close it? When process running in Job tries for any reson to write to stderr it will eventually produce errors.

Also RUN_COLLECT_ERRORS is useful feature and it would solve this issue in our case but I see no way how to pass this flag to tester jobs. What am I missing?

**Comment by MartinMystikJonas** [comment] 2022-07-08 11:00
As solution I would suggest never close stderr of job and make RUN_COLLECT_ERRORS either default behaviour or add CLI parameter to turn it on (--collect-errors? --collect-stderr?)

I could prepere PR if you want.

**Comment by milo** [comment] 2022-07-08 11:01
The reason was unpredictable behaviour as I wrote earlier there, process hangouts.

**Comment by MartinMystikJonas** [comment] 2022-07-08 11:05
@milo Unpredistable behaviour as unpredictalbe order or outputs? Even if stderr is ignored we do not have to close it no? Also when there is both etdout and stderr we can print it something like this:
```
STDOUT:
1
3
STDERR:
2
4
```
I have seem this solution used in some tools.

I am not sure what you mean by process hangouts.

**Comment by milo** [comment] 2022-07-08 13:51
Sorry, I'm on mobile only... Unpredictable stability. It used to be at least. When stderr was too long, reading from stdout got stuck. Whole process got stuck and has to be killed.

Maybe using `2>&1` is the solution. Just merge stdout and stderr into one.

**Comment by MartinMystikJonas** [comment] 2022-07-08 14:26
@milo Actually solution with `2>&1` was my first PR for Nette tester 8 years ago :-) But it was rejected because there were some issues with it too.

See 
https://github.com/nette/tester/issues/86
https://github.com/nette/tester/pull/89

**Comment by MartinMystikJonas** [comment] 2022-07-08 14:37
@milo Is this bug still an issue? I reread discussion in #86 nad PHP bug that caused it https://bugs.php.net/bug.php?id=64438 might be fixed since 2014-09-29

**Comment by milo** [comment] 2022-07-09 06:34
Well, it looks like we can try it.

**Comment by MartinMystikJonas** [comment] 2022-07-10 16:08
Ok any idea how we can test it? Just run Job that outputs huge stdout and stderr?

**Comment by dg** [comment] 2022-07-10 16:37
I tried, it doesn't work even in PHP 8.1.

**Comment by MartinMystikJonas** [comment] 2022-07-10 16:55
Damn. Can you sum up how you tested it?

**Comment by MartinMystikJonas** [comment] 2022-07-10 16:58
What about that old idea of redirecting stderr to temp file?

**Comment by milo** [comment] 2022-07-10 17:27
Since we introduced temporary dir, it is possible. But how to show it/test it? Print it whole when test finished? Or test it separated by new annotation? Or redirect stdout and stderr into the same file and print it, so emulate behaviour of standalone test?

I have no use case for it so I don't know.

**Comment by MartinMystikJonas** [comment] 2022-07-10 18:06
IMHO best option would be reditect both stdout and stderr to same file. But last time we discussed it @db did not liked this idea and wanted separated captures.

So I would go for separate capture and keep current behaviour already used with RUN_COLLECT_ERRORS.

And I would output it same way as we output stdout. Just in case there is stderr i would append something like:

````
some
std
output

--- STDERR ---
some
error
output
```

I can draft PR and then we can finalize it.

**Comment by dg** [comment] 2022-07-10 18:11
test.phpt:

```php
<?php file_put_contents('php://stderr', str_repeat('e', 5030));
```

Job.php line 127:

```php
//		if ($flags & self::RUN_COLLECT_ERRORS) {
			$this->stderr = $stderr;
//		} else {
//			fclose($stderr);
//		}
```

**Comment by MartinMystikJonas** [comment] 2022-07-10 21:00
I drafted PR #438 with capture of stderr to temp file and added STDERR to test output. Updated tests included.

**Closed** 2022-07-21 12:53 UTC
